site_name: TrueLink Documentation
site_description: A Python library for extracting true/final URLs from shortened links
site_author: Mehedi Hasan Shojib
site_url: https://5hojib.github.io/truelink

repo_name: 5hojib/truelink
repo_url: https://github.com/5hojib/truelink
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  markdown_extensions:
    - toc:
      permalink: False

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: material/link-variant
    repo: fontawesome/brands/github

# Plugins
plugins:
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/5hojib
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/truelink
    - icon: fontawesome/brands/telegram
      link: https://t.me/username

extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 5hojib
      repo: truelink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - 'Getting Started': 'user-guide/getting-started.md'
    - 'Advanced Usage': 'user-guide/advanced-usage.md'
    - 'Configuration': 'user-guide/configuration.md'
  - API Reference:
    - 'Core': 'api-reference/core.md'
    - 'Exceptions': 'api-reference/exceptions.md'
  - Contributing: contributing.md
  - Changelog: changelog.md