name: Format and test code with uv

on: 
  push:
    branches:
      - beta
      - dev
    workflow_dispatch:
  pull_request:


jobs:
  lint-format-and-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run ruff to lint and format code
        run: |
          uv run ruff check . --exit-zero
          uv run ruff format .

      - name: Run ty to type check code
        run: |
          uv run ty check .

      - name: Commit and push changes
        run: |
          git config --global user.name "5hojib"
          git config --global user.email "yesiamshojib@gmail.com"
          git add uv.lock
          git add -u
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "format: auto-format code by ruff. [no ci]" --signoff
            git push origin ${{ github.ref }}
          fi
